In [1]:
pip install pandas shapely

Requirement already satisfied: pandas in c:\users\mouad\anaconda3\lib\site-packages (1.4.4)
Collecting shapely
  Downloading shapely-2.0.6-cp39-cp39-win_amd64.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\mouad\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\mouad\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\mouad\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\mouad\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: shapely
Successfully installed shapely-2.0.6
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
from shapely.geometry import Point

df = pd.read_excel('City.xlsx')

In [9]:
df.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Casablanca,Casablanca,33.5333,-7.5833,Morocco,MA,MAR,Casablanca-Settat,admin,3499000,1504175315
1,Fès,Fes,34.0433,-5.0033,Morocco,MA,MAR,Fès-Meknès,admin,1112072,1504861997
2,Marrakech,Marrakech,31.6300,-8.0089,Morocco,MA,MAR,Marrakech-Safi,admin,966987,1504172585
3,Tangier,Tangier,35.7767,-5.8039,Morocco,MA,MAR,Tanger-Tétouan-Al Hoceïma,admin,947952,1504861504
4,Sale,Sale,34.0333,-6.8000,Morocco,MA,MAR,Rabat-Salé-Kénitra,NaN,850403,1504989034

In [11]:
# Fonction pour transformer la longitude et latitude en WKT (Well-Known Text)
def lat_lng_to_wkt(lat, lng):
    point = Point(lng, lat)  # Créer un point avec la longitude et la latitude
    return point.wkt  # Convertir le point en format WKT

# Appliquer la fonction à chaque ligne du DataFrame
df['WKT'] = df.apply(lambda row: lat_lng_to_wkt(row['lat'], row['lng']), axis=1)

# Sauvegarder les données avec la nouvelle colonne WKT dans un nouveau fichier CSV
df.to_csv('City_WKT.csv', index=False)

In [12]:
df.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,WKT
0,Casablanca,Casablanca,33.5333,-7.5833,Morocco,MA,MAR,Casablanca-Settat,admin,3499000,1504175315,POINT (-7.5833 33.5333)
1,Fès,Fes,34.0433,-5.0033,Morocco,MA,MAR,Fès-Meknès,admin,1112072,1504861997,POINT (-5.0033 34.0433)
2,Marrakech,Marrakech,31.6300,-8.0089,Morocco,MA,MAR,Marrakech-Safi,admin,966987,1504172585,POINT (-8.0089 31.63)
3,Tangier,Tangier,35.7767,-5.8039,Morocco,MA,MAR,Tanger-Tétouan-Al Hoceïma,admin,947952,1504861504,POINT (-5.8039 35.7767)
4,Sale,Sale,34.0333,-6.8000,Morocco,MA,MAR,Rabat-Salé-Kénitra,NaN,850403,1504989034,POINT (-6.8 34.0333)